### PR TITLE
chore: update pnpm to v9.14.0

### PR DESCRIPTION
**Pull request by KaiSpencer**

### CODE REVIEW

**Comment by kettanaito** [comment]
Thanks for opening this one, @KaiSpencer! I've bumped the pnpm version to be the current latest, which is 9.14.0. Once the build is green, I will merge this.

**Comment by KaiSpencer** [comment]
> Thanks for opening this one, @KaiSpencer! I've bumped the pnpm version to be the current latest, which is 9.14.0. Once the build is green, I will merge this.

No Problem @kettanaito,

Some WS tests failing now, are you expecting flakes? Vitest has marked one of them flakey

**Comment by kettanaito** [comment]
No, I don't expect flakes in those tests. Need to take a closer look at them.

**Comment by kettanaito** [comment]
## Released: v2.6.7 🎉

This has been released in v2.6.7!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.6.7)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.6.7)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
