### PR TITLE
fix: output a single formatted message to console

### LINKED ISSUE #1795: Style `console` outputs using ANSI Escape Codes
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Hey team, 

thank you for the great work on this library! 

I think we could switch some of console styling ([example](https://github.com/mswjs/msw/blob/a54138a62a7e89bd5f768d369e6b5bc4c46686ae/src/core/handlers/GraphQLHandler.ts#L182-L189)) to use [ANSI Escape Codes](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797) to broaden the compatibility of the output. While the current approach works well when previewed in Chromium-like Dev Tools—piping the console output using tools such as `puppeteer` might not preserve it.

A similar argument can be proposed to also pre-format any string in console outputs instead of relying on format specifiers.

Example when parsing the console output using `puppeteer.ConsoleMessage.text` function below:

```
[MSW] %s %s %s (%c%s%c) 19:50:06 POST https://app.myDomain.com/some-route color:#69AB32 200 OK color:inherit
```

Happy to make a contribution if there's appetite for this change.

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #1795

### CODE REVIEW

**Comment by kettanaito** [comment]
Hi, @signorettif 👋 Could you please give this build a try in your project to see if it resolves the formatting issue? Let me know.

**Comment by kettanaito** [comment]
Okay, there's a bug currently. This is not correct: 

Screenshot 2023-11-01 at 15 50 10

**Comment by kettanaito** [comment]
## Released: v2.0.2 🎉

This has been released in v2.0.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.0.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.0.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by signorettif** [comment]
Amazing work @kettanaito, thank you!

**Pull request merged**
