### PR TITLE
feat: support TypeScript 5.3 for msw 1.3.x (#1875)

### LINKED ISSUE #1875: Bump "typescript": ">= 4.7.x <= 5.2.x" to "typescript": ">= 4.7.x <= 5.3.x"
### Scope

Improves an existing behavior

### Compatibility

- [ ] This is a breaking change

### Feature description

Following recent typescript upgrade would be nice to upgrade the peer dep requirement so that build do not break.

### PR DESCRIPTION
**Pull request by SerkanSipahi**
closes #1875 and #2025

### CODE REVIEW

**Comment by SerkanSipahi** [comment]
@kettanaito any updates regarding this MR? 🙃✌️

**Comment by mattcosta7** [comment]
> @kettanaito any updates regarding this MR? 🙃✌️

should this be based off of main or a v1 tag/branch (if there is one?)

**Comment by SerkanSipahi** [comment]
> ...you can checkout the v1.3.2 [tag](https://github.com/mswjs/msw/tree/v1.3.2) and branch from it. On that feature branch, make the changes and ping me to review them. Once they are reviewed, I can make a backport release to v1.

@mattcosta7 see discussion #1875

**Comment by SerkanSipahi** [comment]
@kettanaito any updates?

**Comment by kettanaito** [comment]
I'm addressing this in https://github.com/mswjs/msw/pull/2086. It also merges to the new `backport/v1` branch that has been configured to release the backport versions for v1 automatically on merge. This will be closed.

**Comment by kettanaito** [comment]
## Released: v0.0.1 🎉

This has been released in v0.0.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.0.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.0.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by kettanaito** [comment]
## Released: v1.3.3 🎉

This has been released in v1.3.3!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v1.3.3)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/1.3.3)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by SerkanSipahi** [comment]
@kettanaito thank you so much :)

**Comment by kettanaito** [comment]
Darn, that comment from the release is not correct. You should use `msw@backport`, not latest. Need to do something about it.

**Comment by SerkanSipahi** [comment]
@kettanaito msw@1.3.3 is also working or has backport a different purpose?

**Comment by kettanaito** [comment]
@SerkanSipahi, you can either pin to an exact version of use `"msw": "backport"` in your package JSON to get any v1 backports automatically. It's up to you. I don't imagine there being many of them. v1 is pretty much in a deprecated readonly mode from now on.

**Pull request closed without merging**
