### PR TITLE
fix: use EventTarget-based event emitter

### LINKED ISSUE #1519: update strict-event-emitter to at least v0.3.x to avoid implicit dependency on Node.js type definitions.
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Firefox

### Reproduction repository

https://github.com/chrisguttandin/msw-test

### Reproduction steps

Run the following commands:

```sh
mkdir msw-test
cd msw-test 
npm init --yes
npm install msw
npm install typescript --save-dev
tsc --init --skipLibCheck false --target es2022 --types " "
touch index.ts
```

Open `index.ts` and add the following content:

```ts
// index.ts
import { setupWorker } from 'msw';

setupWorker;
```

Compile the project:

```sh
tsc -p tsconfig.json
```

### Current behavior

```txt
node_modules/strict-event-emitter/lib/StrictEventEmitter.d.ts:1:30 - error TS7016: Could not find a declaration file for module 'events'. '.../msw-test/node_modules/events/events.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/events` if it exists or add a new declaration (.d.ts) file containing `declare module 'events';`

1 import { EventEmitter } from 'events';
```

### Expected behavior

I would expect it to compile.

### PR DESCRIPTION
**Pull request by chrisguttandin**
- Closes #1519 

This PR intended to update `strict event emitter` to the latest version.

### CODE REVIEW

**Comment by kettanaito** [comment]
@chrisguttandin, thanks for this update! Looks awesome.

Please, have you by any chance noticed if any of MSW dependencies use an older version of `strict-event-emitter`? I'm curious about the Interceptors package in particular.

**Comment by chrisguttandin** [comment]
Running `npm ls strict-event-emitter` only reveals `@mswjs/interceptors` as another user of `strict-event-emitter`.

This is what it looks like with this PR.

```txt
msw@0.49.2
├─┬ @mswjs/interceptors@0.17.5
│ └── strict-event-emitter@0.2.4
└── strict-event-emitter@0.4.3
```

**Comment by kettanaito** [comment]
Nice! I think that shouldn't be the issue since the old strict-event-emitter had problems in the browser. It always worked fine in Node because it was originally based off the native `EventEmitter` (which is not a thing in the browser). 

This should have us good to go!

**Review by kettanaito — APPROVED** [review]

**Comment by kettanaito** [comment]
## Released: v0.49.3 🎉

This has been released in v0.49.3!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.49.3)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.49.3)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by dustinmyers** [comment]
This may be causing errors now - see #1539

**Pull request merged**
