### PR TITLE
fix: support typescript 4.4.x, 4.5.x, 4.6.x

### PR DESCRIPTION
**Pull request by kettanaito**
Adds support for TypeScript 4.4, 4.5, 4.6.

- Follow-up to #1244 
- Closes #1241

### CODE REVIEW

**Comment by starman-vlad** [comment]
@kettanaito I do not wish to sound impatient, but can we expect a new version release today?

**Comment by kettanaito** [comment]
@unigazer, yes. This library is released automatically every day.

**Comment by kentcdodds** [comment]
Thank you!

**Comment by kettanaito** [comment]
## Released: v0.40.2 🎉

This has been released in v0.40.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.40.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.40.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
