### PR TITLE
feat: use `picocolors` instead of `chalk`

### PR DESCRIPTION
**Pull request by Namchee**
## Overview

This pull request replaces `chalk` with `picocolors`, a smaller alternative with the same API that will reduce install size from [97kB](https://pkg-size.dev/chalk@4.1.2) to [6.4kB](https://pkg-size.dev/picocolors)

[More benchmarks on picocolors](https://github.com/alexeyraspopov/picocolors?tab=readme-ov-file#benchmarks)

### CODE REVIEW

**Review by kettanaito — DISMISSED** [review]
Hi, @Namchee. Thanks for proposing this! Looks good to me. Need to try this out locally to see that the colors function as expected. We don't have tests asserting colors of the output, afaik.

**Review by kettanaito — DISMISSED** [review]

**Comment by kettanaito** [comment]
Finally fixed the failing E2E test by stripping the color tokens from the stdout/stderr during the assertions. This is ready for merge! 🚀

**Review by kettanaito — APPROVED** [review]

**Comment by kettanaito** [comment]
Welcome to contributors, @Namchee! Thanks for making MSW more lightweight.

**Comment by kettanaito** [comment]
## Released: v2.7.0 🎉

This has been released in v2.7.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.7.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.7.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by Netail** [comment]
What about https://nodejs.org/docs/latest/api/util.html#utilstyletextformat-text-options :)

**Pull request merged**
