### PR TITLE
fix(setupWorker): warn on multiple "worker.start" and "worker.stop" calls

### LINKED ISSUE #990: Duplicate logging in developer console with worker.start() command
## Describe the bug

As a user, when I start the worker using worker.start(), I expect the [MSW] Mocking Enabled messaging displays in the developer console one time. 

As a user, when I start the worker using worker.start(), if the worker is already started I do not expect additional I expect the [MSW] Mocking Enabled messaging to display in the developer console one time. 

## Environment

- `msw: 0.35.0`
- `nodejs: 16.13.0`
- `npm: 8.1.0`

> Please also provide your browser version.

## To Reproduce
1. Clone this repository: [https://github.com/Capocaccia/cypressMswExample/tree/multiMSWLogExample](https://github.com/Capocaccia/cypressMswExample/tree/multiMSWLogExample)
2. Run the yarn start command
3. The developer console will display multiple [MSW] Mocking Enabled messages due to worker.start() being called multiple times in index.js

## Expected behavior
The [MSW] Mocking Enabled messaging appears only one time. Subsequent calls of worker.start() would provide messaging indicating that MSW is already enabled. This will communicate to the developer that the start command is being called multiple times and it is not necessary.

## Screenshots
Screen Shot 2021-11-18 at 11 03 35 AM

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #990

### CODE REVIEW

**Comment by kettanaito** [comment]
`setupServer` API has no logging on `listen`/`close` to begin with.

**Comment by Capocaccia** [comment]
Thanks for the work on this!

**Comment by kettanaito** [comment]
Thanks for suggesting this, @Capocaccia! I'm glad to push the DX of the library a little further.

**Comment by kettanaito** [comment]
## Released: v0.40.0 🎉

This has been released in v0.40.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.40.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.40.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
