### PR TITLE
feat(package): update typescript to v4.8

### LINKED ISSUE #1376: Support TypeScript 4.8
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.), Firefox, Safari

### Reproduction repository

N/A

### Reproduction steps

N/A

### Current behavior

When trying to update TypeScript to 4.8 (Just released today), we are warned that msw has a peerDependency range for typescript of `>= 4.2.x <= 4.7.x`. As such, it's a pain to force update TypeScript. There's no reason that msw should restrict the maximum TypeScript version we can use in our projects.

### Expected behavior

It looks like this can be traced to msw features that require a minimum TS version (eg: #429).

Two solutions:

* Easy quick fix: Specify a minimum TS version in the peerDependencies but no maximum version
* Better long-term fix: Use the package.json [typesVersions](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions) field to specify different type declaration files depending on the version of TS that someone is running. So if msw wants to use a new feature, they can create a new version of the types which is only used by users with compatible TS versions installed.

### PR DESCRIPTION
**Pull request by dargmuesli**
- Closes #1376

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey, @dargmuesli! Thanks for opening this. I've seen other developers requesting 4.8 support so this is definitely on our roadmap (see #1376). Let's see whether our current source code can compile on 4.8 without issues.

**Comment by dargmuesli** [comment]
Everyone: feel free to add/suggest the necessary changes for the builds to run successfully!
I've added ts 4.8 to the build matrix as well.

**Comment by dargmuesli** [comment]
Hey @kettanaito, I've resolved the typing issues I think. Has been fairly straight-forward, but maybe check if the array addition in https://github.com/mswjs/msw/pull/1375/files#diff-7b84dd6c401e1aad989a92df223139b02211125ef773060498e026b464c2b3c1R38 (in context/set) is ok this way 👋

**Comment by kettanaito** [comment]
Hey, @dargmuesli. You are absolutely fantastic! 🎉 Will check that.

**Comment by dargmuesli** [comment]
The dependency `type-fest` was outdated. Updated it, now the test compilation runs fine on my machine as well. Missed that before.

**Comment by kettanaito** [comment]
Great find! Thanks. Let's see if these changes are also compatible with other versions of TypeScript we support 👀 

Maybe we should establish a policy that adding a new version removes the oldest one automatically. We should have the fixed number of supported projects anyway to keep our heads sane. No need to do this now but something to consider.

**Comment by dargmuesli** [comment]
Great, looks like all tests pass! :partying_face:

**Review by kettanaito — APPROVED** [review]
A superb work done! Thank you, @dargmuesli. Welcome to contributors 🎉

**Comment by kettanaito** [comment]
## Released: v0.46.0 🎉

This has been released in v0.46.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.46.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.46.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
