### PR TITLE
docs: fix readme badges underline

### PR DESCRIPTION
**Pull request by dnicolson**
Before:
PixelSnap 2024-05-15 at 00 06 20@2x

After:
PixelSnap 2024-05-15 at 00 08 01@2x

### CODE REVIEW

**Comment by kettanaito** [comment]
Hi, @dnicolson. Can you please tell me more about what this actually changes? I did my best to A/B your screenshots and code but they look identical to me. Thanks.

**Comment by dnicolson** [comment]
On WebKit/Blink browsers empty whitespace in an anchor tag results in an underline.

Removing the whitespace fixes this.

**Comment by franky47** [comment]
The _before_ tags have better vertical alignment of the text inside the tag IMHO.

**Comment by kettanaito** [comment]
@franky47, that looks like some rendering shenanigans. Looks okay if you open the feature branch.

**Review by kettanaito — APPROVED** [review]
This looks great! Thank you for fixing this, @dnicolson 👏

**Comment by kettanaito** [comment]
## Released: v2.3.1 🎉

This has been released in v2.3.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.3.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.3.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
