### PR TITLE
Splits CI pipeline into workflows

### LINKED ISSUE #247: Split CI pipeline
## Changes

1. Split CI pipeline to include `bootstrap`, `test:unit`, `test:integration`.
1. Add a new `test:smoke` step, that would checkout the [examples repo](https://github.com/mswjs/examples), bootstrap it, and install the `msw` from the tarball of the current release version (not the latest published version).

## Pipeline outlines

```
bootstrap
  ├─ build
    ├─ test:integration
    ├─ test:smoke
  ├─ test:unit
```

### PR DESCRIPTION
**Pull request by kettanaito**
## Changes

- Splits our CI pipeline into a workflow as described in the issue's description.
- Adds a new job called `test-smoke`, that would checkout the Examples repo, install the locally built version of the `msw` package, and run the tests in the Example repo, to make sure current changes do not break any examples.

## GitHub

- Resolves #247

### CODE REVIEW

**Comment by kettanaito** [comment]
All is god, just the smoke test fails to install the locally packed version of `msw`. Neither of the following commands work in the Examples monorepo:

- `lerna add file:/path/to/file`
- `yarn workspaces run add file:/path/to/file`
- `cd examples/<EXAMPLE_NAME> && yarn add file:/path/to/file`

Whenever I use the `file:` protocol, npm/Yarn resolves the package location relative to the `pwd`, regardless if I give it a relative path:

```bash
$ yarn add file:/msw-0.19.5.tgz
// Cannot resolve module from internet or cache: absolutely/weird/path/that/i/did/not/provide
```

**Comment by kettanaito** [comment]
## Technical insights

- `yarn workspaces run *` runs the command in a working directory equal to each workspace (not the CWD where you run the actual `yarn workspaces` command). 
- `yarn add file:*` accepts a path that is bluntly joined with the CWD, regardless if that's a relative or absolute path (can lead to a weird paths like (`/cwd/path/~/absolute/path`)

**Comment by kettanaito** [comment]
## Solution

1. Copy the archived `msw-{COMMIT_HASH}.tgz` file into the cloned examples repository.
1. Unarchive the package.
1. Install the package in all workspaces via `yarn workspaces run add file:./package/` (this respects the `package.json[name]`, while `lerna add ./package` doesn't).

**Comment by kettanaito** [comment]
The smoke test does introduce a slight overhead, as if a change breaks any of the examples, you cannot update the example before the change it released (examples rely on a published package version). I'll make `test-smoke` job optional, and would treat it as a red light, but not necessarily a show-stopper. 

The workflow of a broken example can be as follows:

1. Spot the broken example.
1. Merge the `msw` changes (if everything else is OK).
1. Open an issue in the Examples repo to update and cover the example.
1. Publish the changes.
1. Update the Examples repo.

**Comment by kettanaito** [comment]
Experiencing failing CI: for some reason when `yarn workspaces run add` runs on the CI, it drops the `workspaces` part, and attempts to run `yarn run add`, which tried to resolve the `add` script and fails:

```bash
Installing local package in the workspace...
 
> graphql-react-apollo
 
error Command "add" not found.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
 
Exit code: 1
 
Command: /usr/local/bin/node
Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js run add file:/root/examples/package --no-lockfile
Directory: /root/examples/examples/graphql-react-apollo
Output:
```

**Comment by kettanaito** [comment]
Raised an issue in the Yarn repo: https://github.com/yarnpkg/yarn/issues/8207

**Comment by kettanaito** [comment]
Such deviation of behavior between Yarn `1.22.x` and `1.19.x` is a known issue, and it has been recommended to circumvent it by installing an explicit version of Yarn during CI.

**Comment by kettanaito** [comment]
The pipeline is configured. The Storybook example is edited (see https://github.com/mswjs/examples/pull/19).

**Comment by marcosvega91** [comment]
very good 👍

**Comment by kettanaito** [comment]
Indeed! Having each PR tested against the current Examples we publicly suggest to your users is the key to catching regressions before they occur. I'm a huge fan of example-as-test pattern, and these changes is a nice touch towards incorporating examples as a source of truth even more. 

Thanks for bearing through this with me, @marcosvega91!

**Pull request merged**
