### PR TITLE
Reworks "captureConsole" API for tests

### PR DESCRIPTION
**Pull request by kettanaito**
## Motivation

- Current `captureConsole` accepts the Array argument that it later mutates.
- Also refactors certain tests to be shallow and have each test scenario as a standalone reproducible test.

## Changes

The `captureConsole` function now returns the `messages`, where all captured console messages are sorted in groups ("info", "log", "warning", etc.).

```js
const { messages } = captureConsole(runtime.page)
const neededMessage = messages.error.find(text => text.startsWith('Oops'))
```

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey, @marcosvega91 👋 Sorry for troubling, would you have a minute to review these changes?

**Comment by marcosvega91** [comment]
Hey for me is ok 😄 . There is only a thing that I can't review because is not in the updated code, but I think that you can change in this PR.

There are some point in the code where `test.page.on('console')` is used. I think that you can change this part  
For example
https://github.com/mswjs/msw/blob/f41a1e2641417aa2286b49a2e2d6eaa8c1498978/test/msw-api/integrity-check.test.ts#L24-L28

**Review by marcosvega91 — CHANGES_REQUESTED** [review]
Hey for me is ok 😄 . There is only a thing that I can't review because is not in the updated code, but I think that you can change in this PR.

There are some point in the code where `test.page.on('console')` is used. I think that you can change this part  
For example
https://github.com/mswjs/msw/blob/f41a1e2641417aa2286b49a2e2d6eaa8c1498978/test/msw-api/integrity-check.test.ts#L24-L28

**Comment by kettanaito** [comment]
Thanks for the review!

I've remove the plain usage of `page.on('console')` from the tests in favor of `captureConsole`. Adjusted the `filterLibraryLogs` predicate to be shorthand passable to the `.filter()` Array method.

**Review by marcosvega91 — APPROVED** [review]
LGTM

**Pull request merged**
