### PR TITLE
Issue #145 ctx.fetch() not keeping original headers

### LINKED ISSUE #145: ctx.fetch() not keeping original headers
## Describe the bug
When mocking a REST API using `rest.get` i have a request containing headers, specifically "Authorization" header, and when i call `ctx.fetch()` with this request, in order to get the original response, i have an unauthorized response.
This is due to the fact that my "Authorization" header is missing.

After taking a look at `src/context/fetch.ts`, specifically the `augmentRequestInit()` function, it seems that the type of my request headers is `Headers`, and not `string[][]` nor `Record<string, string>` (see `HeadersInit`type).
I think that the spread operator is not working for the type `Headers`, therefore the headers are not kept :
```typescript
const augmentRequestInit = (requestInit: RequestInit): RequestInit => {
  return {
    ...requestInit,
    headers: {
      ...requestInit.headers,
      'x-msw-bypass': 'true',
    },
  }
}
```

## Environment

- `msw: 0.15.5`
- `nodejs: 12.16.1`
- `npm: 6.13.4`

- browser version: Chrome `81.0.4044.129`

## To Reproduce
1. make a request with "Authorization" header in an authent context
2. call `ctx.fetch()` function with the original request
3. you will see an "401 Unauthorized (from ServiceWorker)" request in your network

My mock :
```typescript
rest.get('/path/to/my/resource', async (req, res, ctx) => {
        const mockedResponse = [
            "Val 1",
            "Val 2",
            "Val 3"
        ];

        const originalResponse = await ctx.fetch(req)

        return res(
            ctx.status(200),
            ctx.json(originalResponse && originalResponse.length ? originalResponse : mockedResponse)
        );
    })
```

## Expected behavior
Headers are kept.

## Temporary Solution
I implemented my own `fetch()` duplicating the existing one, and i change the implementation of the `augmentRequestInit()` function.
My working version :
```typescript
const augmentRequestInit = (requestInit: RequestInit): RequestInit => {
    const headersCopy: Record<string, string> = {}
    if (requestInit.headers instanceof Headers) {
        requestInit.headers.forEach((value: string, name: string) => {
            headersCopy[name] = value
        });
    }
    
    // TODO handle the other types : string[][] and Record<string, string>

    return {
        ...requestInit,
        headers: {
            ...headersCopy,
            'x-msw-bypass': 'true',
        },
    }
}
```

### PR DESCRIPTION
**Pull request by juhanakristian**
- Fixes #145 

Added some unit tests for augmentRequestInit but there's probably room for improvement here. @kettanaito let me know what you think.

Integration tests are still needed.

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey, @juhanakristian. Thank you for those changes! I've taken a brief look and they look great. I'll review in more detail sometime new week. Will help you with the integration tests as well.

**Comment by kettanaito** [comment]
I've added an integration test to the changes (https://github.com/mswjs/msw/pull/149/commits/fd256a9475d8444e360e32c241792d023f8f7470), take a look, if you are interested. Basically, I'm creating a new response patching scenario (the origin of the issue), where a mocked request is forwarded to an actual server (run locally via WDS), while that server has a conditional response based on the `req.headers.authorization`.

What we test here is that `req.headers.authorization` is propagated to the performed request by `ctx.fetch()` utility.

**Review by kettanaito — APPROVED** [review]
These changes are awesome. Once again thank you and welcome to contributors! 🎉

**Comment by juhanakristian** [comment]
Thanks @kettanaito I'll check the integration test to better understand what's going on. 
Hope I get to contribute more in the future 🙂

**Comment by kettanaito** [comment]
@juhanakristian, sounds awesome. Looking forward to your contributions!

In the integration test I establish a custom endpoint (in webpack dev server) that returns different response based on the `req.headers.authorization`. Then I supply those authorization headers to the request issuing function (`rest.request()`), and assert the response assuming the headers are propagated properly.

**Pull request merged**
