### PR TITLE
fix: update `@inquirer/confirm` to 4.0

### PR DESCRIPTION
**Pull request by greysteil**
The only change between v3 and v4 is [allowing the prefix for the confirm message](https://github.com/SBoudrias/Inquirer.js/pull/1544) to be changed, which msw doesn't use. (Alternatively we could widen the supported range here to `^3.0.0 || ^4.0.0`, but it looks like msw generally specifies a single major version it supports.)

The main benefit of the change will be to get access to https://github.com/SBoudrias/Inquirer.js/pull/1569 once it lands (or to make it easier to do so if that is released in a new major version). That will reduce development build size for lots of apps which are currently getting two versions of `@types/node` due to this dependency.

### CODE REVIEW

**Comment by kettanaito** [comment]
Hi, @greysteil 👋  Thanks for submitting this. I think this looks great.

**Review by kettanaito — APPROVED** [review]

**Comment by kettanaito** [comment]
Publishing it as a fix. No user-facing changes present.

**Comment by kettanaito** [comment]
## Released: v2.4.13 🎉

This has been released in v2.4.13!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.4.13)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.4.13)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by ravicious** [comment]
It looks like we still need one more bump to `@inquirer/confirm@5.0.0` which depends on `@inquirer/core@10.0.0` which no longer has `@types/node` in deps. Compare dep graphs for [4.0.1](https://npmgraph.js.org/?q=%40inquirer%2Fconfirm%404.0.1) and [5.0.0](https://npmgraph.js.org/?q=%40inquirer%2Fconfirm%405.0.0).

**Comment by kettanaito** [comment]
@ravicious sounds good. Pull requests are welcome!

**Comment by greysteil** [comment]
All yours @ravicious (or I'll take it if you're busy)

**Comment by ravicious** [comment]
I have to yield as I don't have enough free time at work to take care of this, but I do appreciate your effort!

**Comment by greysteil** [comment]
Done in https://github.com/mswjs/msw/pull/2325

**Pull request merged**
