### PR TITLE
fix: remove duplicate response logging in the browser console

### LINKED ISSUE #1411: Duplicate log output and MaxListenersExceededWarning warning (regression in 0.47.1)
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.), Firefox

### Reproduction repository

https://github.com/kleinfreund/kuma-gui/tree/feat/rework-dataplanes-view

### Reproduction steps

1. In package.json, change the msw dependency from `0.47.0` to `^0.47.3`
2. Run `yarn install`
3. Run `yarn run dev`
4. Browse around the UI and observe the console log entries

### Current behavior

Many redundant log entries appear for requests that are only made once (and handled once). Example:

```
RestHandler.ts:183 [MSW] 09:08:29 GET http://localhost:5681/ (200 OK)
```

The following warning appears:

```
events.js:46 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response:mocked listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (http://localhost:8080/node_modules/.vite/deps/msw.js?v=9b1b86e7:597:19)
    at StrictEventEmitter2.addListener (http://localhost:8080/node_modules/.vite/deps/msw.js?v=9b1b86e7:608:14)
    at StrictEventEmitter2.once (http://localhost:8080/node_modules/.vite/deps/msw.js?v=9b1b86e7:868:36)
    at Object.onMockedResponse (http://localhost:8080/node_modules/.vite/deps/msw.js?v=9b1b86e7:22101:34)
ProcessEmitWarning		@	events.js:46
_addListener			@	events.js:219
addListener			@	events.js:227
StrictEventEmitter2.once	@	StrictEventEmitter.js:34
onMockedResponse		@	createRequestListener.ts:76
await in onMockedResponse (async)		
handleRequest			@	handleRequest.ts:127
await in handleRequest (async)		
(anonymous)			@	createRequestListener.ts:34
(anonymous)			@	setupWorker.ts:93
```

### Expected behavior

The logs aren't unnecessarily redundant and there is no max listeners exceeding warning.

### Notes

- Likely cause as the only change between 0.47.0 and 0.47.1: https://github.com/mswjs/msw/pull/1392
- Initially reported in https://github.com/mswjs/msw/issues/1343#issuecomment-1246566445
- Code that reproduces the issue **does not** import msw/node

### PR DESCRIPTION
**Pull request by snaka**
Update `strict-event-emitter` version that to resolve log duplicates.

- Fixes #1411
- https://github.com/open-draft/strict-event-emitter/pull/2

### CODE REVIEW

**Comment by kettanaito** [comment]
Thanks for adding this, @snaka!
We need to also add an integration test for this, as our CI didn't catch this issue being merged.

**Comment by snaka** [comment]
@kettanaito 

I have a problem with that.
I don't know how to write or run Integration test.
Especially when I run integration test locally, I get the following error and all tests fail. 

image

I ran `yarn build` before the test.
This is the situation on my current main branch.

My working environment is Windows (WSL2).
Is that the cause of the problem?

The tests run by GitHub Actions seemed to be using a virtual macOS, so I was wondering about that.

**Comment by snaka** [comment]
I followed the message and ran `test:integration` with the `--detectOpenHandles` option.

It seems that I am missing some libraries in my environment.

```
      Missing libraries we didn't find packages for:
          libexpat.so.1
          libgcc_s.so.1
```

I will install these libraries and give it a try.

image

**Comment by snaka** [comment]
Sorry.
It's still going to take a while to get Playwright to work on my Windows 10!
I will keep trying, but if you have any other suggestions, I would appreciate your advice.

**Comment by kettanaito** [comment]
Hey, @snaka. No worries. I know it can be challenging to run PW on other systems. I will checkout your branch and help you with the test when I have a minute.

**Comment by snaka** [comment]
Thanks @kettanaito . It is very helpful.

**Comment by kettanaito** [comment]
I've added the integration test for this fix 👍 Also found some shared state issue in the existing unit test, fixed that as well (I believe that one has been failing the CI).

**Comment by kettanaito** [comment]
I've found another issue that `events.removeAllListeners()` didn't actually remove the listeners. Fixed in https://github.com/open-draft/strict-event-emitter/releases/tag/v0.2.6.

**Comment by kettanaito** [comment]
Thank you for helping fix this, @snaka! Welcome to contributors.

**Comment by snaka** [comment]
Thank you @kettanaito for your support.
Glad to hear the problem was resolved quickly!

**Comment by kettanaito** [comment]
## Released: v0.47.4 🎉

This has been released in v0.47.4!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.47.4)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.47.4)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
