### PR TITLE
Fixes response patching of POST request

### LINKED ISSUE #77: Response patching for POST does not work
Using ctx.fetch inside the response resolver for a POST results in a GET being sent (with no body) instead of a POST (with a body).

Notes:
- The req before sending the original request showed the correct body and bodyUsed:true, but looking at the req in mockServiceWorker showed the body gone.  
I suspect the problem is in context/fetch.ts, but initial scan did not show an obvious issue to me (JavaScript beginner)

I wrote an integration test to PR into the repo that replicated the issue, but I did not have permission to push up a branch.

## Tests:

```ts
// response-mocking.mocks.ts:
 rest.post(
  'https://jsonplaceholder.typicode.com/posts',
  async (req, res, ctx) => {
    const originalResponse = await ctx.fetch(req)
    return res(
      ctx.json({
        ...originalResponse,
        mocked: true,
      }),
    )
  },
),
```
```ts
// response-patching.test.ts:
describe('given a post request to be patched', () => {
  it('should be able to properly request and patch a post', async () => {
    const REQUEST_URL = 'https://jsonplaceholder.typicode.com/posts'

    api.page.evaluate(
      (url) =>
        fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            title: 'foo',
            body: 'bar',
            userId: 1,
          }),
        }),
      REQUEST_URL,
    )
    const res = await api.page.waitForResponse((res) => {
      return (
        // Await for the response from MSW, so that original response
        // from the same URL would not interfere.
        res.url() === REQUEST_URL && res.headers()['x-powered-by'] === 'msw'
      )
    })
    const body = await res.json()

    expect(res.status()).toBe(200)
    expect(body).toEqual({
      id: 101,
      title: 'foo',
      body: 'bar',
      userId: 1,
      mocked: true,
    })
  })
})

### PR DESCRIPTION
**Pull request by kettanaito**
> Original pull request: #78 

## GitHub

- Fixes #77

### CODE REVIEW

**Comment by kettanaito** [comment]
Hi, @skipdavis1117. Sorry for closing your original pull request (#78), I've got stuck with rebasing your remote branch and couldn't push the new state of the commits tree.

> My guess is that I couldn't push to your remote because the changes were residing on `master`. It hasn't happened before when pushing to remote feature branches.

If you don't mind, I've opened this follow-up with your commits preserved. Thanks for understanding.

**Comment by kettanaito** [comment]
## Solution

I've looked into this issue and spotted that on the Service Worker level right before dispatching a bypassed request it operated on the `GET` request, despite the original `request` being of method `POST`. This was related to the destructuring of the `request` Object. Apparently, if you destructure a POST request it produces a GET request.

https://github.com/open-draft/msw/blob/16e536a22de1be266cd038c2811dae2d7fb71ecd/src/mockServiceWorker.js#L102-L105

When the request object is passed to the `Request` constructor directly, it inherits the method and other properties accordingly.

I've also used the `requestClone` in the bypassed request handling to prevent "request already sent" and similar errors. I think it's generally a good practice in terms of intermittent request handling.

**Comment by kettanaito** [comment]
@skipdavis1117, could you please review this change so we could merge it? Thanks.

**Comment by skipdavis1117** [comment]
No worries, you could just ask me to do it.  I'd be happy to instead of
making more work for you.  I am more interested in working product than my
feelings. I have not had much time to troubleshoot this week, but I think
you were right that the problem is likely in the Request creation and not
in the fetch.  I'll have a little more time this weekend.

Thanks

**Comment by kettanaito** [comment]
@skipdavis1117, hey, absolutely no worries! You add no extra work for me. I've discovered a fix while debugging, so I decided to push it and not trouble you. The tests you've contributed are great, I'm extremely thankful!

There are a few open issues, if you have time take a look at any of them and voice your opinion. Ones I would recommend to look are #21, #55 (discussion mainly).

**Comment by skipdavis1117** [comment]
Great!  I'll look at those

**Review by skipdavis1117 — APPROVED** [review]
Looks good.

**Pull request merged**
