### PR TITLE
fix(cli): support windows paths in the `init` command

### LINKED ISSUE #2218: Add cross platform path support to workerDirectory
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

20.15.1

### Reproduction repository

-

### Reproduction steps

To reproduce my problem you will need both a Mac and a Windows computer.
You need to write path with slashes in msw.workerDirectory in package.json. For example: 
```
package.json
{
  ...,
  "msw": {
    "workerDirectory": "public/sw"
  },
  ...
}
```
And run your application with msw

### Current behavior

On windows we get this message

image

On Mac we have `Service Worker successfully created!`

### Expected behavior

We have `Service Worker successfully created!` on each computers

### PR DESCRIPTION
**Pull request by ivanfernandez2646**
- Fixes #2218

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey, @ivanfernandez2646 👋 Thank you so much for adding the tests!

I've pushed the fix so now the `init` command can support both Windows and Unix paths stored in `workerDirectory` or provided as an argument in the CLI.

**Review by kettanaito — APPROVED** [review]
This looks great! Waiting for the CI before merging.

**Comment by kettanaito** [comment]
Welcome to the contributors, @ivanfernandez2646 👏

**Comment by kettanaito** [comment]
## Released: v2.4.2 🎉

This has been released in v2.4.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.4.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.4.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by nabby27** [comment]
Congratulations @ivanfernandez2646 for your contribution!

Although it is not a solution to the issue (since the problem did not exist), I will still pay you the [Opire bounty](https://app.opire.dev/issues/01J4MNDT6938BJ4Q8BFX8NG8MQ) for contributing to the project by creating the tests!

**Comment by ivanfernandez2646** [comment]
@kettanaito @nabby27 Many thanks!! It was a pleasure!

**Pull request merged**
