### PR TITLE
fix: prevent `instanceof` handler check failures between different MSW versions

### LINKED ISSUE #2346: Interception broken due to `instanceof` handlers check (dual publish)
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/funes79/nocode

### Reproduction steps

I tested 2.4.0, 2.3.0,  2.5.0, all works as expected. But upgrade to 2.6.0 breaks intercepting, in client components:

```
[MSW] Warning: intercepted a request without a matching request handler:

  • GET https://github.com/reviews2

If you still wish to intercept this unhandled request, please create a request handler for it.
Read more: https://mswjs.io/docs/getting-started/mocks
```

handlers file: 
```
import { http, HttpResponse } from 'msw';

export const handlers = [
  http.get('*.js', () => passthrough()),
  http.get('github.com/reviews2', () => {
    console.log('MSW reviews2');
    // return HttpResponse.text('Hello, World!');
    return HttpResponse.json({ reviews: 'Hello, World2!' });
  }),
];
```

### Current behavior

[MSW] Warning: intercepted a request without a matching request handler:

GET https://github.com/reviews2

### Expected behavior

Should return: 
{"reviews":"Hello, World!"}
[MSW] 14:41:28 GET https://github.com/reviews2 (200 OK)

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #2346 

## Roadmap

- [x] Use the same pattern for filtering WebSocket handlers ([ref](https://github.com/mswjs/msw/pull/2349#issuecomment-2460086220)).

### CODE REVIEW

**Review by patricklafrance — APPROVED** [review]

**Comment by robbtraister** [comment]
do you also want to use this pattern for filtering the websocket handlers?

https://github.com/mswjs/msw/blob/main/src/core/ws/handleWebSocketEvent.ts#L33

**Comment by kettanaito** [comment]
@robbtraister, thanks, that's a fantastic point. Will adjust the solution.

**Comment by robbtraister** [comment]
this is awesome! I really appreciate the effort on this.

**Comment by kettanaito** [comment]
@patricklafrance @robbtraister can you please give this [preview release](https://github.com/mswjs/msw/pull/2349#issuecomment-2460500795) a try and let me know if the issue is fixed on your end? I would publish the changes then. Thanks.

**Comment by robbtraister** [comment]
@kettanaito it works for me! 🎉

**Comment by patricklafrance** [comment]
@kettanaito I am not sure what's going on, I'll have to investigate but at the moment NO requests at all are being intercepted, not even those for the HOST app request handlers.

The issue might be on on my side though, I'll have to investigate later today.

**Comment by kettanaito** [comment]
@patricklafrance, you mentioned you have different frontends loading different versions of MSW. If that's the case, none of the older versions will include `__kind` in their handlers, so this change will still ignore them. 

I highly encourage you to update MSW across the board. I presume you are at v2 already so it should be a breeze.

**Comment by patricklafrance** [comment]
@kettanaito they are all on the same version in my sample application that I used for testing this new version.

**Comment by kettanaito** [comment]
## Released: v2.6.1 🎉

This has been released in v2.6.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.6.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.6.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by kettanaito** [comment]
Oh, that's interesting! Is that reproducible in the example you shared with me?

**Comment by patricklafrance** [comment]
@kettanaito I think it was something about how I installed the PR package (https://pkg.pr.new/msw@2349). Not sure what happened but i tried with `2.6.1` and everything works fine. So happy, thank you very much for the quick fix :)

**Comment by patricklafrance** [comment]
> Oh, that's interesting! Is that reproducible in the example you shared with me?

It's fixed with `2.6.1` but yes it was reproducible with the example I shared with you. This is the one I used.

**Pull request merged**
