### PR TITLE
ci(workflows): upgrade actions/checkout and actions/setup-node to v3

### PR DESCRIPTION
**Pull request by oscard0m**
# Description
* `ci.yml`
  * Upgrade `actions/checkout` from `v2` to `v3`
  * Upgrade `actions/setup-node` from `v2` to `v3`
* `smoke.yml`
  * Upgrade `actions/checkout` from `v2` to `v3`
  * Upgrade `actions/setup-node` from `v2` to `v3`

### CODE REVIEW

**Review by kettanaito — APPROVED** [review]
A superb change. Thank you, @oscard0m! Welcome to contributors 🎉 

Please, if you see any places in our CI we can improve, do not hesitate to raise a pull request or a discussion. 

One particular problematic area I'm dealing with right now is automated cron releases with `semantic-release`. I'm having trouble for `semantic-release` to create a version commit and push it to Git. Although I'm signing that commit as myself (admin), it still fails to push with the "require 2 check to pass" (branch protection rules) errors.

**Comment by oscard0m** [comment]
> A superb change. Thank you, @oscard0m! Welcome to contributors 🎉

Thanks for the quick review and lovely feedback!

> Please, if you see any places in our CI we can improve, do not hesitate to raise a pull request or a discussion.

Sure, I will :)

> One particular problematic area I'm dealing with right now is automated cron releases with `semantic-release`. I'm having trouble for `semantic-release` to create a version commit and push it to Git. Although I'm signing that commit as myself (admin), it still fails to push with the "require 2 check to pass" (branch protection rules) errors.

Interesting, is there an issue/discussion talking about this? If not, I can open one where we can talk and discuss if you want. @kettanaito

**Comment by oscard0m** [comment]
> Please, if you see any places in our CI we can improve, do not hesitate to raise a pull request or a discussion.
> 
Can we do a spike checking the cache evolution with [this](https://github.blog/changelog/2022-03-17-view-cache-usage-in-your-action-workflows/)?

**Comment by kettanaito** [comment]
@oscard0m, yeah, you can open a discussion around automated releases, I can contribute with the current state of the setup. 

> Can we do a spike checking the cache evolution with [this](https://github.blog/changelog/2022-03-17-view-cache-usage-in-your-action-workflows/)?

Do you propose we monitor it somehow? I'd like to learn more.

**Comment by kettanaito** [comment]
## Released: v0.40.0 🎉

This has been released in v0.40.0!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.40.0)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.40.0)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
